[package]
name = "proj4rs"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"
description = "Rust adaptation of Proj4js"
readme = "./README.md"
keywords = ["gis", "proj", "projection", "geography", "geospatial"]

[dependencies]
thiserror = "1.0"
lazy_static = { version = "1", optional = true }
log = { version = "0.4", optional = true, features = ["release_max_level_info"] }

[dev-dependencies]
approx = "0.5"
criterion = { version = "0.3" }
env_logger = "0.3.3"

[profile.release]
lto = true
codegen-units = 1

[lib]
crate_type = ["cdylib", "rlib"]

[features]
multi-thread = ["lazy_static"]
logging = ["log"]
local_tests = []

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
wee_alloc = "0.4"
console_log = "0.2"

[[bench]]
name = "bench_proj"
harness = false
