[package]
name = "proj4rs"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"
description = "Rust adaptation of Proj4js"
readme = "./README.md"
keywords = ["gis", "proj", "projection", "geography", "geospatial"]

[dependencies]
thiserror = "1.0"

[dev-dependencies]
approx = "0.5"
criterion = { version = "0.3" }

[profile.release]
lto = true
codegen-units = 1

[lib]
crate_type = ["cdylib", "rlib"]

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = "0.2"
wee_alloc = "0.4"

[[bench]]
name = "loop_vs_fold"
harness = false
