[package]
name = "proj4rs"
version = "0.1.1"
edition = "2021"
rust-version = "1.66"
description = "Rust adaptation of Proj4"
readme = "./README.md"
keywords = ["gis", "proj", "projection", "geography", "geospatial"]
authors = ["David Marteau <dmarteau@3liz.com>"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/3liz/proj4rs/"
repository = "https://github.com/3liz/proj4rs/"
documentation = "https://docs.rs/proj4rs/"
exclude = [
    "js/*",
    "Makefile.toml",
    "ol-proj4rs-demo-app",
    "fixtures",
    ".docker",
    "PROJ4_General_Parameters.pdf",
    "index.html",
]

[dependencies]
crs-definitions = { version = "0.3", optional = true, default-features = false, features = ["proj4"] }
thiserror = "1.0"
lazy_static = { version = "1", optional = true }
log = { version = "0.4", optional = true  }
geo-types = { version = "0.7.12", optional = true }

[dev-dependencies]
approx = "0.5"
criterion = { version = "0.5" }
env_logger = "0.10"
clap = { version = "4", features=["derive"] }
log = "0.4"

[profile.release]
lto = true
codegen-units = 1

[lib]
crate_type = ["cdylib", "rlib"]

[features]
default = ["multi-thread"]
multi-thread = ["lazy_static"]
geo-types = ["dep:geo-types"]
logging = ["log"]
local_tests = []
wasm-strict = []
proj4js-compat = []

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["console"] }
wee_alloc = "0.4"
console_log = "1.0"

[[bench]]
name = "bench_proj"
harness = false

[[example]]
name = "rsproj"
