[tasks.default]
alias = "defaults"

[tasks.defaults]
dependencies = [
    "build"
]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.wasm]
script = [
    "wasm-pack build --target web --no-default-features --features=proj4js-compat"
]


[tasks.wasm_debug]
script = [
    "wasm-pack build --target web --no-default-features --features=logging --features=proj4js-compat --features=with-wasm-entrypoint"
]

[tasks.wasm_strict]
script = [
    "wasm-pack build --target web --no-default-features --features=wasm-strict --features=proj4js-compat"
]

# Build for webpack bundle
[tasks.wasm_bundle]
script = [
    "wasm-pack build --target bundler -d pkg-bundle --no-default-features --features=proj4js-compat"
]

