#
# See 
# * https://github.com/mozilla/cbindgen/blob/master/template.toml
# * https://github.com/mozilla/cbindgen/blob/master/docs.md
#
language = "C"

include_guard =" _PROJ4RS_H_"

cpp_compat = true
documentation_style = "c99"
