[tasks.default]
alias = "defaults"

[tasks.defaults]
dependencies = [
    "build"
]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks."build-release"]
command = "cargo"
args = ["build", "--release"]

[tasks.cbindgen]
command = "cbindgen"
args = [
    "--config", "cbindgen.toml",
    "--crate",  "proj4rs-clib",
    "--output", "../target/cbindgen/proj4rs.h",
    "--quiet",
]

[tasks.deb]
command = "cargo"
args = [
    "deb",
    "--profile", "release",
    "--no-separate-debug-symbols",
    "--no-strip",
    "--no-build",
]
dependencies = ["build-release", "cbindgen"]

[tasks.release]
dependencies = ["deb"]


[tasks."python.lint"]
command = "ruff"
args = [
    "check",
    "--output-format", "concise",
    "python",
]


[tasks."python.lint-fix"]
command = "ruff"
args = [
    "check",
    "--preview",
    "--fix",
    "python",
]


[tasks."python.typing"]
command = "mypy"
args = ["python"]


[tasks."python.test"]
command = "pytest"
args = [ "-v", "python/tests"]
dependencies = ["python.lint", "python.typing"]
