[tasks.default]
alias = "defaults"

[tasks.defaults]
dependencies = [
    "build"
]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.release]
command = "cargo"
args = ["build", "--release"]

[tasks.doc]
command = "cargo"
args = ["doc", "--all-features", "--no-deps"]

#
# WASM
#

[tasks.wasm]
command = "wasm-pack"
args = [
    "build",
    "--target=web",
    "--no-default-features",
    "--features=proj4js-compat",
]


[tasks.wasm_debug]
command = "wasm-pack"
args = [
    "build", 
    "--target=web",
    "--no-default-features",
    "--features=logging",
    "--features=proj4js-compat",
    "--features=with-wasm-entrypoint",
]

[tasks.wasm_strict]
command = "wasm-pack"
args = [
    "build",
    "--target=web",
    "--no-default-features",
    "--features=wasm-strict",
    "--features=proj4js-compat",
]


# Build for webpack bundle
[tasks.wasm_bundle]
command = "wasm-pack"
args = [
    "build",
    "--target=bundler",
    "-d", "pkg-bundle",
    "--no-default-features",
    "--features=proj4js-compat",
]

