[tasks.default]
alias = "defaults"

[tasks.defaults]
dependencies = [
    "build"
]

[tasks.build]
description = "Dev build"
command = "cargo"
args = ["build"]

[tasks.release]
description = "Release build"
command = "cargo"
args = ["build", "--release"]

[tasks.doc]
description = "Build documentation"
command = "cargo"
args = ["doc", "--all-features", "--no-deps"]

#
# WASM
#

[tasks.wasm]
description = "Build wasm module (web target)"
command = "wasm-pack"
args = [
    "build",
    "--out-dir=../js/pkg",
    "--release",
    "--target=web",
    "--no-default-features",
    "--features=proj4js-compat",
]


[tasks.wasm_debug]
description = "Build wasm module with logging feature (web target)"
command = "wasm-pack"
args = [
    "build", 
    "--out-dir=../js/pkg",
    "--dev",
    "--target=web",
    "--no-default-features",
    "--features=logging",
    "--features=proj4js-compat",
    "--features=with-wasm-entrypoint",
]

[tasks.wasm_strict]
description = "Build wasm module in strict-mode (web target)"
command = "wasm-pack"
args = [
    "build",
    "--out-dir=../js/pkg",
    "--release",
    "--target=web",
    "--no-default-features",
    "--features=wasm-strict",
    "--features=proj4js-compat",
]


[tasks.wasm_bundle]
description = "Build wasm package as nodejs bundle"
command = "wasm-pack"
args = [
    "build",
    "--out-dir=../js/pkg-bundle",
    "--release",
    "--target=bundler",
    "--no-default-features",
    "--features=proj4js-compat",
]

