name: 📖 Documentation

on:
  push:
#    tags:
#      - '*'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

jobs:
  proj4rs-demo:
    name: "🟨 Proj4rs demo"
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install WASM pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
          version: 'latest'

      - name: WASM Pack
        working-directory: proj4rs
        run: wasm-pack build --target web --release --out-dir=../js/pkg --no-default-features --features=proj4js-compat

      - name: Install Node
        uses: actions/setup-node@v4

      - name: Npm update
        working-directory: js/ol-proj4rs-demo-app
        run: npm --loglevel=verbose update

      - name: Npm build
        working-directory: js/ol-proj4rs-demo-app
        run: |
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: js/ol-proj4rs-demo-app/dist

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Summary
        if: github.ref == 'refs/heads/main'
        run: |
          echo "
            ### Published ! :rocket:
          
            [Visit the doc](https://docs.3liz.org/proj4rs/)
          " >> $GITHUB_STEP_SUMMARY
